# Generated by Django 2.0.4 on 2018-06-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200, verbose_name='标题')),
                ('blog_body', models.TextField(verbose_name='正文')),
                ('blog_time', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '博文',
                'verbose_name_plural': '博文',
            },
        ),
    ]
